# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bydlení Mukařov
description: Levné bydlení v obci Mukařov - Srbín v klidném prostředí, 30km od centra Prahy.
keywords: Bydlení Mukařov, Byty Mukařov, Domy, na prodej, simekostav, u prahy, bydlení, bydlenimukarov.cz, Mukařov, Srbín, levné bydlení, řadové rodinné domy, byty, terasa
author: arkun.xyz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bydlenimukarov.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
